<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Product extends Model
{
    protected $fillable = ['name', 'code', 'price', 'status'];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($product) {
            $product->user_id = Auth::id();
        });
    }

    public function users()
    {
        return $this->belongsTo('App/User');
    }

    public function suppliers()
    {
        return $this->belongsToMany('App\Supplier')->withTimestamps();
    }

}
